# Generated by Django 4.0.1 on 2022-04-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Set',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('publicity', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=7)),
                ('set_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Audiovisual',
            fields=[
                ('mat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='material.material')),
                ('external_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('length', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Material',
            fields=[
                ('mat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='material.material')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Periodical_Material',
            fields=[
                ('mat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='material.material')),
                ('pages', models.IntegerField()),
                ('period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Printed',
            fields=[
                ('mat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='material.material')),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
