# Generated by Django 4.0.1 on 2022-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('hw', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('due', models.DateTimeField()),
            ],
        ),
    ]
