# Generated by Django 4.0.1 on 2022-04-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_outsidemember_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMaterialRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('new_mat_title', models.CharField(max_length=50)),
                ('new_mat_author', models.CharField(max_length=50)),
                ('is_custom', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('in_consideration', 'in_consideration'), ('accepted', 'accepted'), ('denied', 'denied'), ('completed', 'completed')], default='in_consideration', max_length=20)),
                ('librarian_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.librarian')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='AskRequest',
            fields=[
                ('ask_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField(max_length=250)),
                ('reply', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('unanswered', 'unanswered'), ('answered', 'answered')], default='unanswered', max_length=20)),
                ('librarian_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.librarian')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
