# Generated by Django 4.0.1 on 2022-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmaterialrequest',
            name='librarian_id',
        ),
        migrations.RemoveField(
            model_name='newmaterialrequest',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AskRequest',
        ),
        migrations.DeleteModel(
            name='NewMaterialRequest',
        ),
    ]
