# Generated by Django 4.0.1 on 2022-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_newmaterialrequest_librarian_id_and_more'),
        ('user', '0005_alter_outsidemember_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='outsidemember',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registrar_id',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='OutsideMember',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
