# Generated by Django 4.0.1 on 2022-05-03 22:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0006_remove_librarian_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('registrar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.mainuser')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.mainuser')),
                ('office', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=4)),
                ('tenure', models.CharField(choices=[('Prof', 'Professor'), ('Assoc. Prof', 'Assoc Prof'), ('Asst. Prof', 'Asst Prof'), ('Inst', 'Instructor')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.mainuser')),
                ('specialization', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OutsideMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.mainuser')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('card_no', models.IntegerField(unique=True)),
                ('expire_date', models.DateField(default=datetime.datetime(2022, 5, 4, 1, 7, 55, 700165))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.mainuser')),
                ('department', models.CharField(max_length=16)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
