# Generated by Django 4.0.1 on 2022-05-03 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsidemember',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 1, 9, 20, 13017)),
        ),
    ]
