# Generated by Django 4.0.1 on 2022-05-03 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_outsidemember_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='registrar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outsidemember',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 2, 5, 54, 186740)),
        ),
    ]
