# Generated by Django 4.0.1 on 2022-05-03 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_mainuser_registrar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsidemember',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 2, 32, 12, 267629)),
        ),
    ]
