# Generated by Django 4.0.1 on 2022-05-04 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_outsidemember_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsidemember',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 13, 41, 8, 928449)),
        ),
    ]
